import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  NbActionsModule,
  NbAlertModule,
  NbAutocompleteModule,
  NbBadgeModule,
  NbButtonModule,
  NbCardModule,
  NbCheckboxModule,
  NbContextMenuModule,
  NbDatepickerModule,
  NbFormFieldModule,
  NbIconModule,
  NbInputModule,
  NbLayoutModule,
  NbListModule,
  NbMenuModule,
  NbPopoverModule,
  NbSearchModule,
  NbSelectModule,
  NbSidebarModule,
  NbSpinnerModule,
  NbTagModule,
  NbThemeModule,
  NbTooltipModule,
  NbUserModule,
} from '@nebular/theme';
import { NbEvaIconsModule } from '@nebular/eva-icons';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    NbSelectModule,
    NbIconModule,
    NbButtonModule,
    NbInputModule,
    NbDatepickerModule,
    NbListModule,
    NbCardModule,
    NbContextMenuModule,
    NbPopoverModule,
    NbTooltipModule,
    NbFormFieldModule
  ],
  exports: [
    NbSelectModule,
    NbIconModule,
    NbButtonModule,
    NbInputModule,
    NbDatepickerModule,
    NbListModule,
    NbCardModule,
    NbContextMenuModule,
    NbPopoverModule,
    NbTooltipModule,
    NbAutocompleteModule,
    NbLayoutModule,

    NbSidebarModule,
    NbIconModule,
    NbMenuModule,
    NbThemeModule,
    NbAlertModule,
    NbLayoutModule,
    NbActionsModule,
    NbSelectModule,
    NbLayoutModule,
    NbMenuModule,
    NbUserModule,
    NbActionsModule,
    NbSearchModule,
    NbSidebarModule,
    NbContextMenuModule,
    NbButtonModule,
    NbIconModule,
    NbEvaIconsModule,
    NbTooltipModule,
    NbAutocompleteModule,
    NbBadgeModule,
    NbTagModule,
    NbSpinnerModule,
    NbAlertModule,
    NbDatepickerModule,
    NbCheckboxModule,
    NbFormFieldModule
  ],
})
export class NebularComponentsModule {}
